config/routes.rb
Cuckoo::Application.routes.draw do

  resources :proposals do
    resources :votes
    resources :guest_passes, :only => [:create]
    resources :choices
  end

  match '/guest_passes/:token' => 'guest_passes#use', :as => 'use_guest_pass'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :proposal
  
  def to_s
    label
  end
end

app/models/guest_pass.rb
require 'token_generator'

class GuestPass < ActiveRecord::Base
  before_create :generate_token

  belongs_to :proposal

  private
  def generate_token
    self.token = TokenGenerator.friendly_token
  end
end

app/models/proposal.rb
require 'unanimity'

class Proposal < ActiveRecord::Base
  cattr_accessor :default_protocol do
    Unanimity.name
  end

  has_many :votes
  has_one :guest_pass
  has_many :choices

  def protocol
    (protocol_class || Proposal.default_protocol).constantize.new
  end

  def shared?
    !guest_pass.nil?
  end

  def guest_pass_token
    guest_pass.try(:token)
  end

  def outcome
    protocol.tally(breakdown)
  end

  def breakdown
    choices.each_with_object({}) { |choice, breakdown| breakdown[choice] = votes.cast_as(choice).count }
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :proposal

  scope :cast_as, lambda { |choice| where(:value => choice.label) }

  def choice
    value.intern
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_filter :find_proposal

  def create
    @choice = @proposal.choices.build(params[:choice])
    @choice.save!
    redirect_to(@proposal)
  end
  
  private
  def find_proposal
    @proposal = Proposal.find(params[:proposal_id].to_i)
  end

end

app/controllers/guest_passes_controller.rb
class GuestPassesController < ApplicationController

  def create
    @proposal = Proposal.find(params[:proposal_id])
    guest_pass = @proposal.build_guest_pass
    guest_pass.save!
    redirect_to(@proposal)
  end

  def use
    guest_pass = GuestPass.find_by_token(params[:token])
    @proposal = guest_pass.proposal
    @vote = Vote.new
    render 'votes/new'
  end
end

app/controllers/proposals_controller.rb
require 'unanimity'
require 'majority'

class ProposalsController < ApplicationController
  respond_to :html

  def index
    respond_with(@proposals = Proposal.all)
  end

  def new
    @proposal = Proposal.new
    @protocols = [ Unanimity.new.to_s, Majority.new.to_s ]
  end

  def create
    proposal = Proposal.new(params[:proposal])
    proposal.save!
    redirect_to(proposals_path)
  end

  def show
    respond_with(@proposal = Proposal.find(params[:id]), @choice = Choice.new)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :find_proposal

  respond_to :html

  def new
    respond_with(@vote = Vote.new)
  end

  def create
    vote = @proposal.votes.build(params[:vote])
    vote.save!
    redirect_to(proposals_path)
  end

  private
  def find_proposal
    @proposal = Proposal.find(params[:proposal_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/guest_passes_helper.rb
module GuestPassesHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def visualize_results(container, proposal)
    series = proposal.breakdown.keys.collect { |key| key.label }
    data = proposal.breakdown.values

    raw <<-EOJS
      <script type="text/javascript">
          var chart = new cuckoo.charting.Votes();
          chart.visualize("#{container}", #{series.to_json}, #{data.to_json});
      </script>
    EOJS
  end
end

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

    = csrf_meta_tag
    = yield(:head)

  %body{:class => controller.controller_name}
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/proposals/_proposal.html.haml
%h2 Proposition
.subject
  Subject:
  = @proposal.subject
.wording
  Wording:
  = @proposal.wording

.protocol
  Protocol:
  = @proposal.protocol

.choices
  Available choices:
  %ul
    - @proposal.choices.each do |choice|
      %li
        = choice.label

app/views/proposals/index.html.haml
= link_to "New proposal", new_proposal_path

%h2 Proposals
%table#proposals
  %tr
    %th Subject
    %th Protocol
    %th Outcome

  - @proposals.each do |proposal|
    %tr[proposal]
      %td= link_to proposal.subject, proposal_path(proposal)
      %td= proposal.protocol
      %td= proposal.outcome
      %td= link_to "Vote", new_proposal_vote_path(proposal)

app/views/proposals/new.html.haml
%h2 New proposal

= semantic_form_for @proposal do |form|
  = form.inputs do
    = form.input :subject
    = form.input :wording
    = form.input :protocol_class, :as => :select, :collection => @protocols

  = form.buttons do
    = form.commit_button :button_html => { :id => 'proposal_submit' }
    %li.cancel
      or
      = link_to 'cancel', proposals_path

app/views/proposals/show.html.haml
= link_to "All proposals", proposals_path()

= render @proposal

Add a new choice:
= semantic_form_for [@proposal, @choice] do |form|
  = form.inputs do
    = form.input :label
  = form.buttons do
    = form.commit_button 'Add this choice'

- if @proposal.shared?
  .guest_pass
    Guests can access this proposal using the following link:
    = use_guest_pass_url(@proposal.guest_pass_token)
- else
  = semantic_form_for [@proposal, GuestPass.new] do |form|
    = form.buttons do
      = form.commit_button 'Share'

app/views/votes/_breakdown.html.haml
- @proposal.breakdown.each do |choice, count|
  = count.to_s + " " + choice.to_s

app/views/votes/new.html.haml
= link_to "All proposals", proposals_path()

= render @proposal

%h4 Your vote
= semantic_form_for [@proposal, @vote] do |form|
  = form.buttons do
    - @proposal.choices.each do |choice|
      = form.commit_button choice.label.to_s, :button_html => { :id => choice.label.to_s, :name => "vote[value]" }

#breakdown
  %h4 Current results
  = render "votes/breakdown"

%h4 Casting of votes

#chart
= visualize_results("#chart", @proposal)